window.esdocSearchIndex = [
  [
    "picoes/src/entity.js~entity",
    "class/src/entity.js~Entity.html",
    "<span>Entity</span> <span class=\"search-result-import-path\">picoes/src/entity.js</span>",
    "class"
  ],
  [
    "picoes/src/world.js~world",
    "class/src/world.js~World.html",
    "<span>World</span> <span class=\"search-result-import-path\">picoes/src/world.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/entity.js",
    "file/src/entity.js.html",
    "src/entity.js",
    "file"
  ],
  [
    "src/entity.js~entity#access",
    "class/src/entity.js~Entity.html#instance-method-access",
    "src/entity.js~Entity#access",
    "method"
  ],
  [
    "src/entity.js~entity#attach",
    "class/src/entity.js~Entity.html#instance-method-attach",
    "src/entity.js~Entity#attach",
    "method"
  ],
  [
    "src/entity.js~entity#clone",
    "class/src/entity.js~Entity.html#instance-method-clone",
    "src/entity.js~Entity#clone",
    "method"
  ],
  [
    "src/entity.js~entity#components",
    "class/src/entity.js~Entity.html#instance-get-components",
    "src/entity.js~Entity#components",
    "member"
  ],
  [
    "src/entity.js~entity#constructor",
    "class/src/entity.js~Entity.html#instance-constructor-constructor",
    "src/entity.js~Entity#constructor",
    "method"
  ],
  [
    "src/entity.js~entity#destroy",
    "class/src/entity.js~Entity.html#instance-method-destroy",
    "src/entity.js~Entity#destroy",
    "method"
  ],
  [
    "src/entity.js~entity#detach",
    "class/src/entity.js~Entity.html#instance-method-detach",
    "src/entity.js~Entity#detach",
    "method"
  ],
  [
    "src/entity.js~entity#fromjson",
    "class/src/entity.js~Entity.html#instance-method-fromJSON",
    "src/entity.js~Entity#fromJSON",
    "method"
  ],
  [
    "src/entity.js~entity#get",
    "class/src/entity.js~Entity.html#instance-method-get",
    "src/entity.js~Entity#get",
    "method"
  ],
  [
    "src/entity.js~entity#has",
    "class/src/entity.js~Entity.html#instance-method-has",
    "src/entity.js~Entity#has",
    "method"
  ],
  [
    "src/entity.js~entity#id",
    "class/src/entity.js~Entity.html#instance-get-id",
    "src/entity.js~Entity#id",
    "member"
  ],
  [
    "src/entity.js~entity#id",
    "class/src/entity.js~Entity.html#instance-set-id",
    "src/entity.js~Entity#id",
    "member"
  ],
  [
    "src/entity.js~entity#remove",
    "class/src/entity.js~Entity.html#instance-method-remove",
    "src/entity.js~Entity#remove",
    "method"
  ],
  [
    "src/entity.js~entity#replace",
    "class/src/entity.js~Entity.html#instance-method-replace",
    "src/entity.js~Entity#replace",
    "method"
  ],
  [
    "src/entity.js~entity#set",
    "class/src/entity.js~Entity.html#instance-method-set",
    "src/entity.js~Entity#set",
    "method"
  ],
  [
    "src/entity.js~entity#tojson",
    "class/src/entity.js~Entity.html#instance-method-toJSON",
    "src/entity.js~Entity#toJSON",
    "method"
  ],
  [
    "src/entity.js~entity#valid",
    "class/src/entity.js~Entity.html#instance-method-valid",
    "src/entity.js~Entity#valid",
    "method"
  ],
  [
    "src/entity_storage.js",
    "file/src/entity_storage.js.html",
    "src/entity_storage.js",
    "file"
  ],
  [
    "src/system_storage.js",
    "file/src/system_storage.js.html",
    "src/system_storage.js",
    "file"
  ],
  [
    "src/utilities.js",
    "file/src/utilities.js.html",
    "src/utilities.js",
    "file"
  ],
  [
    "src/world.js",
    "file/src/world.js.html",
    "src/world.js",
    "file"
  ],
  [
    "src/world.js~world#clear",
    "class/src/world.js~World.html#instance-method-clear",
    "src/world.js~World#clear",
    "method"
  ],
  [
    "src/world.js~world#component",
    "class/src/world.js~World.html#instance-method-component",
    "src/world.js~World#component",
    "method"
  ],
  [
    "src/world.js~world#constructor",
    "class/src/world.js~World.html#instance-constructor-constructor",
    "src/world.js~World#constructor",
    "method"
  ],
  [
    "src/world.js~world#context",
    "class/src/world.js~World.html#instance-method-context",
    "src/world.js~World#context",
    "method"
  ],
  [
    "src/world.js~world#each",
    "class/src/world.js~World.html#instance-method-each",
    "src/world.js~World#each",
    "method"
  ],
  [
    "src/world.js~world#entity",
    "class/src/world.js~World.html#instance-method-entity",
    "src/world.js~World#entity",
    "method"
  ],
  [
    "src/world.js~world#run",
    "class/src/world.js~World.html#instance-method-run",
    "src/world.js~World#run",
    "method"
  ],
  [
    "src/world.js~world#system",
    "class/src/world.js~World.html#instance-method-system",
    "src/world.js~World#system",
    "method"
  ]
]